### ISSUE TITLE
SIMOBS-67.1 Convert CRTM TauCoeff and SpcCoeff files from binary to netCDF

### ISSUE THREAD

**Issue by StegmannJCSDA** [JCSDA/CRTMv3#42]
This epic covers the conversion of TauCoeff and SpcCoeff CRTM instrument coefficient files from binary to netCDF format for the case where there is no netCDF file already available.

The following file types need to be converted:

- [ ] TauCoeff
- [ ] SpcCoeff

Conversion scripts for individual files are already available (SpcCoeff and TauCoeff, le -> nc4).
The remaining tasks are:

- [ ] Write a batch script to run the individual Fortran applications over all required instruments ( O(100) ).
- [ ] Run batch script over all cases.
- [ ] Error handling for special cases where the applications fail.

**Comment by chengdang** [comment]
@BenjaminTJohnson, this issue should be closed for now and move to AOP 2024.
