### ISSUE TITLE
[Feature] Operator Overloading for Assignment (=) between Existing and New/Empty Types in CRTM (Fortran)

### ISSUE THREAD

**Issue by BenjaminTJohnson** [JCSDA/CRTMv3#81]
#### Background:

Within the CRTM, there are multiple custom types (e.g., Options_Type) used for various functionalities. Currently, assigning an object of an existing type to an uninitialized or new object of the same type requires explicit member-wise assignment, which can be cumbersome and error-prone.

#### Feature Description:

Implement operator overloading for the assignment operator `=` in Fortran to allow for straightforward assignment between existing and new or uninitialized objects of custom types within CRTM. This will enhance code readability and reduce the risk of errors.

##### Example:

! Current way of doing assignment
```
newObject%member1 = existingObject%member1
newObject%member2 = existingObject%member2
```
! ... and so on

! Proposed way
```
newObject = existingObject
```

#Tasks:
- [ ] Identify all custom types within CRTM where this feature could be beneficial.
- [ ] Implement the overloaded assignment operator = for these types using Fortran's interface assignment construct.

- [ ] Update relevant documentation to reflect this new feature.

- [ ] Write unit tests to verify the correct functionality of the overloaded assignment operator.

Expected Benefits:

 Simplifies code related to object initialization and assignment.

 Reduces the risk of bugs due to member-wise copying.  This was noticed with  Opt = Options assignment.   This becomes particularly problematic when there are allocatable optional components of a given type.   

 Improves maintainability by reducing the amount of code needed for type assignments.

**Comment by BenjaminTJohnson** [comment]
List of custom types eligible for operator assignment, I think choosing only the operators that have an existing `(==)` (equal check) operator should have the assignment `(=)` operator: 

- [ ] .//src/InstrumentInfo/oSRF/PtrArr_Utility/PtrArr_Define.f90:  INTERFACE OPERATOR(==)
- [ ] .//src/InstrumentInfo/oSRF/oSRF_Define.f90:  INTERFACE OPERATOR(==)
- [ ] .//src/InstrumentInfo/Instruments/Subset_Define.f90:  INTERFACE OPERATOR(==)
- [ ] .//src/InstrumentInfo/MW_SensorData/MW_SensorData_Define.f90:  INTERFACE OPERATOR(==)
- [ ] .//src/Options/Zeeman_Input/Zeeman_Input_Define.f90:  INTERFACE OPERATOR(==)
- [ ] .//src/Options/SSU_Input/SSU_Input_Define.f90:  INTERFACE OPERATOR(==)
- [ ] .//src/Options/CRTM_Options_Define.f90:  INTERFACE OPERATOR(==)
- [ ] .//src/AtmOptics/CRTM_AtmOptics_Define.f90:  INTERFACE OPERATOR(==)
- [ ] .//src/AtmOptics/AOvar_Define.f90:  INTERFACE OPERATOR(==)
- [ ] .//src/GeometryInfo/CRTM_GeometryInfo_Define.f90:  INTERFACE OPERATOR(==)
- [ ] .//src/GeometryInfo/CRTM_Geometry_Define.f90:  INTERFACE OPERATOR(==)
- [ ] .//src/Coefficients/EmisCoeff/IR_Water/IRwaterCoeff_Define.f90:  INTERFACE OPERATOR(==)
- [ ] .//src/Coefficients/EmisCoeff/MW_Water/MWwaterLUT/MWwaterLUT_Define.f90:  INTERFACE OPERATOR(==)
- [ ] .//src/Coefficients/EmisCoeff/MW_Water/MWwaterCoeff_Define.f90:  INTERFACE OPERATOR(==)
- [ ] .//src/Coefficients/EmisCoeff/MW_Snow/MWsnowCoeff_Define.f90:  INTERFACE OPERATOR(==)
- [ ] .//src/Coefficients/EmisCoeff/IR_Land/LSEatlas/LSEatlas_Define.f90:  INTERFACE OPERATOR(==)
- [ ] .//src/Coefficients/EmisCoeff/SEcategory/SEcategory_Define.f90:  INTERFACE OPERATOR(==)
- [ ] .//src/Coefficients/NLTECoeff/NLTECoeff_Define.f90:  INTERFACE OPERATOR(==)
- [ ] .//src/Coefficients/BeCoeff/BeCoeff_Define.f90:  INTERFACE OPERATOR(==)
- [ ] .//src/Coefficients/ACCoeff/ACCoeff_Define.f90:  INTERFACE OPERATOR(==)
- [ ] .//src/Coefficients/AerosolCoeff/AerosolCoeff_Define.f90:  INTERFACE OPERATOR(==)
- [ ] .//src/Coefficients/FitCoeff/FitCoeff_Define.f90:  INTERFACE OPERATOR(==)
- [ ] .//src/Coefficients/CloudCoeff/CloudCoeff_Define.f90:  INTERFACE OPERATOR(==)
- [ ] .//src/Coefficients/SpcCoeff/SpcCoeff_Define.f90:  INTERFACE OPERATOR(==)
- [ ] .//src/SfcOptics/CRTM_SfcOptics_Define.f90:  INTERFACE OPERATOR(==)
- [ ] .//src/SfcOptics/IR_Land/IRLSEM/GrELS/GrELS_Define.f90:  INTERFACE OPERATOR(==)
- [ ] .//src/TauProd/AtmProfile/AtmProfile_Define.f90:  INTERFACE OPERATOR(==)
- [ ] .//src/TauProd/LBL/lblrtm/define/LBLRTM_Layer_Define.f90:  INTERFACE OPERATOR(==)
- [ ] .//src/TauProd/LBL/lblrtm/define/LBLRTM_Panel_Define.f90:  INTERFACE OPERATOR(==)
- [ ] .//src/TauProd/LBL/lblrtm/define/LBLRTM_Phdr_Define.f90:  INTERFACE OPERATOR(==)
- [ ] .//src/TauProd/LBL/lblrtm/define/LBLRTM_File_Define.f90:  INTERFACE OPERATOR(==)
- [ ] .//src/TauProd/LBL/lblrtm/define/LBLRTM_Fhdr_Define.f90:  INTERFACE OPERATOR(==)
- [ ] .//src/TauProd/LBL/lblrtm/build/libsrc/LBLRTM_Layer_Define.f90:  INTERFACE OPERATOR(==)
- [ ] .//src/TauProd/LBL/lblrtm/build/libsrc/LBLRTM_Panel_Define.f90:  INTERFACE OPERATOR(==)
- [ ] .//src/TauProd/LBL/lblrtm/build/libsrc/LBLRTM_Phdr_Define.f90:  INTERFACE OPERATOR(==)
- [ ] .//src/TauProd/LBL/lblrtm/build/libsrc/LBLRTM_File_Define.f90:  INTERFACE OPERATOR(==)
- [ ] .//src/TauProd/LBL/lblrtm/build/libsrc/LBLRTM_Fhdr_Define.f90:  INTERFACE OPERATOR(==)
- [ ] .//src/AtmScatter/AerosolScatter/ASvar_Define.f90:  INTERFACE OPERATOR(==)
- [ ] .//src/AtmScatter/CloudScatter/CSvar_Define.f90:  INTERFACE OPERATOR(==)
- [ ] .//src/NLTE/NLTE_Predictor/NLTE_Predictor_Define.f90:  INTERFACE OPERATOR(==)
- [ ] .//src/ChannelInfo/CRTM_ChannelInfo_Define.f90:  INTERFACE OPERATOR(==)
- [ ] .//src/AtmAbsorption/ODPS/PAFV_Define.f90:  INTERFACE OPERATOR(==)
- [ ] .//src/AtmAbsorption/ODPS/ODPS_Predictor_Define.f90:!  INTERFACE OPERATOR(==)
- [ ] .//src/AtmAbsorption/ODAS/ODAS_Predictor_Define.f90:!  INTERFACE OPERATOR(==)
- [ ] .//src/RTSolution/CRTM_RTSolution_Define.f90:  INTERFACE OPERATOR(==)
- [ ] .//src/Surface/CRTM_Surface_Define.f90:  INTERFACE OPERATOR(==)
- [ ] .//src/Surface/Surface_ConvertFormat/CRTM_Surface_Define_old.f90:  INTERFACE OPERATOR(==)
- [ ] .//src/Surface/Surface_ConvertFormat/CRTM_SensorData_Define_old.f90:  INTERFACE OPERATOR(==)
- [ ] .//src/Surface/SensorData/CRTM_SensorData_Define.f90:  INTERFACE OPERATOR(==)
- [ ] .//src/Atmosphere/CRTM_Atmosphere_Define.f90:  INTERFACE OPERATOR(==)
- [ ] .//src/Atmosphere/Aerosol/CRTM_Aerosol_Define.f90:  INTERFACE OPERATOR(==)
- [ ] .//src/Atmosphere/Cloud/CRTM_Cloud_Define.f90:  INTERFACE OPERATOR(==)
- [ ] .//src/Test_Utility/CompTest/CompTest_Define.f90:  INTERFACE OPERATOR(==)
- [ ] .//src/Utility/Solar_Utility/Solar_Define.f90:  INTERFACE OPERATOR(==)

Fun.

**Comment by BenjaminTJohnson** [comment]
probably not going to do this anytime soon, closing this issue as stale.
